//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChitDetail
    {
        public int ChitDetailsId { get; set; }
        public int UsersChitsId { get; set; }
        public Nullable<System.DateTime> MessageDate { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<decimal> PendingAmount { get; set; }
        public Nullable<decimal> ExtraAmount { get; set; }
        public Nullable<decimal> Dividend { get; set; }
        public string OtherNumbers { get; set; }
        public string ReceiptNumber { get; set; }
        public string CheckNumber { get; set; }
        public string Comments { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual UsersChit UsersChit { get; set; }
    }
}
