//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Arrears = new HashSet<Arrear>();
            this.Debits = new HashSet<Debit>();
            this.UtilityPayments = new HashSet<UtilityPayment>();
        }
    
        public int StatusId { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<Arrear> Arrears { get; set; }
        public virtual ICollection<Debit> Debits { get; set; }
        public virtual ICollection<UtilityPayment> UtilityPayments { get; set; }
    }
}
